name: UPX Action
description: GitHub Action to run UPX on an executable
author: tarampampam

branding:
  icon: file-minus
  color: blue

inputs:
  file:
    description: 'Input file'
    required: false
    deprecationMessage: This GitHub action was deprecated
  dir:
    description: 'Input directory'
    required: false
    deprecationMessage: This GitHub action was deprecated
  upx_args:
    description: 'Arguments to pass to UPX'
    required: true

runs:
  using: docker
  image: Dockerfile
